### ISSUE TITLE
Version 2.1.5 - Error

### ISSUE THREAD

**Issue by natedavis** [BF2Statistics/ControlCenter#4]
I am getting the following error...

```
-------- BF2Statistics Exception Trace Log --------
Exception Date: 8/13/2015 6:05:38 PM
Program Version: 2.1.5
Os Version: Microsoft Windows NT 6.1.7601 Service Pack 1
System Type: 64 Bits
RunAs Admin: True
Stats Driver: Sqlite
Gamespy Driver: Sqlite
Selected Mod: bf2

-------- Exception --------
Type: System.Exception
Message: The config key "stats_enable" was not formated correctly.
Target Method: ParseSettings
File: d:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Python\StatsPythonConfig.cs
Line: 152
StackTrace:
   at BF2Statistics.StatsPythonConfig.ParseSettings() in d:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Python\StatsPythonConfig.cs:line 152
   at BF2Statistics.StatsPythonConfig..ctor() in d:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Python\StatsPythonConfig.cs:line 138
   at BF2Statistics.StatsPython.get_Config() in d:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Python\StatsPython.cs:line 51
   at BF2Statistics.MainForm.SetInstallStatus() in d:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Forms\MainForm.cs:line 170
   at BF2Statistics.MainForm..ctor() in d:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Forms\MainForm.cs:line 90
   at BF2Statistics.Program.Main(String[] args) in d:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Program.cs:line 79
```

I was running 1.9.3, I installed 2.1.5, and then uninstalled both and reinstalled 2.1.5. The above error is looking for a file on a D Drive, which I don't have. Wonder if it is looking for a hard coded location...

**Comment by natedavis** [comment]
OK, nevermind. Downloaded the code, built it, and found the problem. Turns out I had config file version 2.2.0 in BF2StatisticsConfig.py  I downloaded 2.1.5, did a fresh install on a new machine. I updated my config file to version 2.3.0, and now everything is running as expected. Thanks for all you do!

**Comment by wilson212** [comment]
I didnt see this issue because you closed it before i seen it. This problem can be alleviated by clicking the "Restore default python files" button on the Bf2 Server tab. Before 2.2, im pretty sure this was impossible to do, but since 2.2, the program will still load up fully, allowing you to "fix"/restore the python issues.
